// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-WhTJiHI_5XqhjG3wZZ7OOkCyEN8yV8',
    appId: '1:107572185107:web:e54fe73ef93a3779a257e6',
    messagingSenderId: '107572185107',
    projectId: 'nzinga-base',
    authDomain: 'nzinga-base.firebaseapp.com',
    storageBucket: 'nzinga-base.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqM6hKgWtN3DoKLNTRWEPCAZ4yUS_WT_4',
    appId: '1:107572185107:android:7fc11e6846c3675fa257e6',
    messagingSenderId: '107572185107',
    projectId: 'nzinga-base',
    storageBucket: 'nzinga-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFViLC05lgzlY3v_FMlb04OBAkSmko3kA',
    appId: '1:107572185107:ios:0294433c38e12f97a257e6',
    messagingSenderId: '107572185107',
    projectId: 'nzinga-base',
    storageBucket: 'nzinga-base.firebasestorage.app',
    iosBundleId: 'com.example.nzingaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFViLC05lgzlY3v_FMlb04OBAkSmko3kA',
    appId: '1:107572185107:ios:0294433c38e12f97a257e6',
    messagingSenderId: '107572185107',
    projectId: 'nzinga-base',
    storageBucket: 'nzinga-base.firebasestorage.app',
    iosBundleId: 'com.example.nzingaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB-WhTJiHI_5XqhjG3wZZ7OOkCyEN8yV8',
    appId: '1:107572185107:web:862996bc6cbbb2e3a257e6',
    messagingSenderId: '107572185107',
    projectId: 'nzinga-base',
    authDomain: 'nzinga-base.firebaseapp.com',
    storageBucket: 'nzinga-base.firebasestorage.app',
  );
}
