// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // This file was generated by flutterfire_cli
import 'package:nzinga_app/auth_screen.dart';
import 'package:nzinga_app/auth_wrapper.dart';

void main() async { // main() now needs to be async
  WidgetsFlutterBinding.ensureInitialized(); // Required before Firebase.initializeApp()
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'N\'zinga App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'Poppins',
      ),
      debugShowCheckedModeBanner: false,
      home: const AuthWrapper(), // Use AuthWrapper as the home screen
    );
  }
}